### ISSUE TITLE
[notice] dbus does not allow qomui.service by default on openSUSE Leap 15.0

### ISSUE THREAD

**Issue by ChaosNicro** [corrad1nho/qomui#52] opened 2018-12-27 16:04 UTC
Using the packaged Version of 0.8.0 the GUI failed to start the service.
Running `sudo qomui-service` manually, I got:

`Traceback (most recent call last):
  File "/usr/bin/qomui-service", line 11, in <module>
    load_entry_point('qomui==0.8.0', 'console_scripts', 'qomui-service')()
  File "/usr/lib/python3.6/site-packages/qomui/qomui_service.py", line 645, in main
    service = QomuiDbus()
  File "/usr/lib/python3.6/site-packages/qomui/qomui_service.py", line 58, in __init__
    self.bus_name = dbus.service.BusName(BUS_NAME, bus=self.sys_bus)
  File "/usr/lib/python3.6/site-packages/dbus/service.py", line 131, in __new__
    retval = bus.request_name(name, name_flags)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 303, in request_name
    'su', (name, flags))
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Connection ":1.143" is not allowed to own the service "org.qomui.service" due to security policies in the configuration file`

I don't know much about the system-dbus but the policy seems to block "unregistered" services by default.
My solution was to create a minimal policy for the service:
**/etc/dbus-1/system.d/org.qomui.conf**
```
<policy>
    <allow own="org.qomui.service"/>
</policy>
```
I'm not actually certain that it is the default setting but I did not change any settings in the dbus-service. Should this be a problem for other users, you may want to place a similar configuration and reload the dbus-service during installation. If this is actually just me, please feel free to close this.
After this change, everything started fine and is working as expected.

Setup used:
Opensuse Leap 15.0
qomui 0.8.0 from corrad1nho's Opensuse repository

**Comment by corrad1nho** [comment] 2018-12-30 13:45
I had this issue in the past; sometimes a restart of dbus (or a system reboot) was necessary in order for the policy file to be recognized properly on some distributions. A custom policy file shouldn't be needed as I already included [one](https://github.com/corrad1nho/qomui/blob/master/systemd/org.qomui.service.conf).

**Comment by corrad1nho** [comment] 2019-01-06 00:19
I did a fresh install of OpenSuse Leap 15 and couldn't reproduce this issue. But I just realized that you are starting qomui-service manually. What happens if you use systemd?
`systemctl start qomui`

**Comment by corrad1nho** [comment] 2019-01-16 00:11
@poisonowl: Please remove and then reinstall Qomui. For detail see #53.

**Comment by corrad1nho** [comment] 2019-02-03 01:37
Deb packages were broken. It's fixed in v0.8.2. A re-install is required, though.

**Closed by corrad1nho** 2019-02-03 01:37 UTC
Labels: bug
